### ISSUE TITLE
Which Version of MM is compatible.

### ISSUE THREAD

**Issue by chengy77** [jupadin/MMM-MQTT#2]
Having issues running. Here's the errors I get.

pi@raspberrypi:~/MagicMirror $ npm start MagicMirror

> magicmirror@2.2.2 start /home/pi/MagicMirror
> sh run-start.sh "MagicMirror"

Starting MagicMirror: v2.2.2
Loading config ...
WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
Loading module helpers ...
App threw an error during load
Error: Cannot find module 'node_helper'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:6:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'node_helper'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:6:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by jupadin** [comment]
Yes, thanks for the issue!
Same problem as in #1.
Just pushed a new version - please do a fresh
```
git pull && npm install
```
and afterwards everything should work as expected.
